services:
  ambistream:
    image: ghcr.io/seprog/ambistream:latest
    build: .
    restart: unless-stopped
    volumes:
      - ./config/:/opt/ambilight/config/:ro
      - ./nginx.conf:/etc/nginx/nginx.conf  # optional
    ports:
      - 1935:1935
